package com.deligence.deli.domain;

public enum EmployeeRole {
    USER, ADMIN, MATERIAL, ORDER, PROCUREMENT, PRODUCT, CLIENT, SUPPLIER, PRODUCTION ;
    //USER 0, ADMIN 1, MATERIAL 2, ORDER 3, PROCUREMENT 4, PRODUCT 5, CLIENT 6, SUPPLIER 7, PRODUCTION 8 로 ROLE_SET에 입력됨
}
